version: 0.2

phases:
  install:
    commands:
      # Install AWS CLI and any other dependencies if needed
      - echo "Installing dependencies.."
      # aws ssm install # Uncomment if you need to install any dependencies

  pre_build:
    commands:
      - echo "Preparing to trigger the existing pipeline..."

  build:
    commands:
      # Trigger the existing pipeline in the first repository
      - echo "Triggering the martini-build-image pipeline test..."
      - aws codepipeline start-pipeline-execution --name martini-upload-package

  post_build:
    commands:
      - echo "Pipeline trigger completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
